[project]
name = "vector-db-access-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "protobuf>=6.31.1",
    "sentence-transformers>=5.0.0",
    "weaviate>=0.1.2",
    "weaviate-client>=4.16.4",
]
